version: '3.8'

volumes:
  pg_data1:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data1:/var/lib/postgresql/data
  
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    build: ./infra/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media/