version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: tychinkamary/foodgram_backend:latest
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
    env_file:
      - ./.env
  
  frontend:
    env_file: .env
    image: tychinkamary/foodgram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  
  gateway:
    image: tychinkamary/foodgram_gateway:latest
    ports:
      - 8000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
