version: '3.3'

volumes:
  pg_data1:
  static:
  media:


services:
  db:
    image: postgres:latest
    env_file: ./.env
    volumes:
      - pg_data1:/var/lib/postgresql/data
  
  backend:
    image: tychinkamary/foodgram_backend:latest
    restart: always
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media
  
  frontend:
    image: tychinkamary/foodgram_frontend:latest
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:latest
    env_file: ./.env
    depends_on:
      - frontend
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/app/media