version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:

services:

  backend:
    image: tychinkamary/foodgram_backend:latest
    restart: always
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  
  frontend:
    image: tychinkamary/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
      - static:/app/result_build/build
  
  nginx:
    image: nginx:1.25.2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

  db:
    image: postgres:13.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env